<?php

namespace AppBundle\Repository;

/**
 * StadiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadiumRepository extends \Doctrine\ORM\EntityRepository{
    
    public function findStadiums($stadiums) {

    $q=$this->createQueryBuilder('c')
    ->where('c.stadium_id = :stadium_id')
    ->setParameter('stadium_id', $stadiums)
    ->getQuery()->getResult();

    return $q;


  }
}
